# Generated by Django 5.1.7 on 2025-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='es_feriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroventa',
            name='es_fin_de_semana',
            field=models.BooleanField(default=False),
        ),
    ]
