# Generated by Django 5.1.7 on 2025-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_ai', '0002_registroventa_es_feriado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='pagado_deuna',
            field=models.BooleanField(default=False),
        ),
    ]
