# Generated by Django 5.1.7 on 2025-03-28 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionequipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcionequipo',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_editados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcionequipo',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
