# Generated by Django 5.1.7 on 2025-04-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='numero_serie',
        ),
    ]
