# Generated by Django 5.1.7 on 2025-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_remove_equipo_numero_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcionequipo',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
