# Generated by Django 5.1.7 on 2025-04-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0004_alter_recepcionequipo_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
